AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Valheim API


Parameters:

  BaseStack:
    Type: String

  DiscordPublicKey:
    Type: String


Resources:

  API:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ AWS::StackName }-api
      Runtime: nodejs12.x
      CodeUri: .
      Handler: ./src/api/handler.handler
      MemorySize: 128
      Timeout: 300
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: ec2:DescribeNetworkInterfaces
              Resource: '*'
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref Secret
            - Effect: Allow
              Action:
                - ecs:*
                - ecs:UpdateService
                - ecs:DescribeServices
                - ecs:ListTasks
                - ecs:DescribeTasks
              Resource: '*'
              Condition:
                StringEquals:
                  'ecs:cluster': !GetAtt Cluster.Arn
      Environment:
        Variables:
          LOG_LEVEL: debug
          CLUSTER:
            Fn::ImportValue: !Sub ${ BaseStack }-cluster-name
          SERVICE:
            Fn::ImportValue: !Sub ${ BaseStack }-service-name
          BUCKET:
            Fn::ImportValue: !Sub ${ SourceStack }-bucket-name
          DISCORD_PUBLIC_KEY: !Ref DiscordPublicKey

Outputs:

  API:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
